name: Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Thanks for taking the time to fill out this bug report for the **ServerRawler Tool**!

        Please fill out the following form to your best ability to help us fix the problem.
        > [!NOTE]
        > Only use this form if you're sure you found a **reproducible bug**.  
        > For support or questions, join our [Discord server](https://discord.gg/vbZ2FKyjMN) or check the [FAQ](https://cyberdolfi.github.io/ServerRawler/docs/FAQ).

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "A clear and concise description of what the bug is."
      placeholder: "When I ..."
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: "To Reproduce"
      description: "Steps to reproduce this behaviour"
      placeholder: |
        1. Start scan with 100 IPs
        2. See error (Or sth. like that)
      value: |
        1. 
        2. 
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: "Expected behaviour"
      description: "A clear and concise description of what you expected to happen."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual behavior"
      description: "Describe what actually happened when you followed the steps you described above."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Log output and (if possible) backtrace"
      description: |
        Copy and paste the full log output — including error messages — as well as any backtrace that are reported.
        What you paste in will be formatted as a code block — so, no need to put code fence backticks around it.
        **DO NOT PASTE YOUR CREDENTIALS IF ITS IN YOUR LOGS**
      placeholder: |
        Console logs:
        [12:15:33] [ERROR   ] Something went wrong: ...
        [12:15:34] [CRIT    ] Another log entry
        [12:16:02] [WARNING ] ...
      value:
      render: shell

  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots or screen recordings"
      description: "Drag and drop in below any screenshots or screen recordings you’ve made which show the problem."

  - type: input
    id: tool-version
    attributes:
      label: "Tool Version"
      description: "What version of the ServerRawler Tool are you running? See Documentation: [Getting Version](https://cyberdolfi.github.com/ServerRawler/docs/getting-version) ***(DO NOT WRITE `latest`)***"
      placeholder: "Version: 0.1.5"
      value: "Version: "
    validations:
      required: true

  - type: input
    id: operation-system
    attributes:
      label: "Operation System"
      description: "On wich OS is ServerRawler running?"
      placeholder: |
        Windows 11 25H2
        Ubuntu 24.04.3 LTS

  - type: checkboxes
    id: will-patch
    attributes:
      label: "Contribute a patch?"
      description: "If you plan to contribute a patch for this issue yourself, please check the box below — to tell us and others looking at the issue that someone’s already working on it."
      options:
        - label: "I'll contribute a patch for this myself."